version: "3"

services:
  bento:
    image: lol_predictor_service:latest
    container_name: bento
    ports:
      - "3000:3000" # API
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  lolpredict_airflow:
    image: apache/airflow:3.0.2-python3.10 #apache/airflow:2.10.3-python3.10

    volumes:
      - ./airflow:/opt/airflow
      - //var/run/docker.sock:/var/run/docker.sock 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - airflow_network

    command: airflow standalone
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
    working_dir: /mlflow/mlruns
    networks:
      - airflow_network
  lol-predict-ml-pipeline:
    build:
      dockerfile: Dockerfile

networks:
  airflow_network:
  monitoring:
volumes:
  lol-predict-airflow-storage:
    driver: local
  grafana-storage:
    driver: local
  
