stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    - configs/data/base.yaml
    - configs/paths/base.yaml
    outs:
    - data/processed/new_data_actual_season.csv
    - data/processed/prev_and_actual_season_data.csv
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/prev_and_actual_season_data.csv
    - configs/data/base.yaml
    - configs/paths/base.yaml
    outs:
    - data/processed/X.csv
    - data/processed/X_next_days.csv
    - data/processed/teams_stats.csv
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/X.csv
    - data/processed/saved_training_data.csv
    - configs/paths/base.yaml
    - configs/tracking/base.yaml
    - configs/model
    outs:
    - models
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
    - models
    - data/processed/saved_training_data.csv
    - configs/model
    - configs/paths/base.yaml
    - configs/tracking/base.yaml
