trained_model: models/lgb_model.pkl
prev_and_actual_season_data: data/processed/prev_and_actual_season_data.csv
processed_x: data/processed/X.csv
processed_x_next_days: data/processed/X_next_days.csv
next_days_prediction: data/processed/next_days_prediction.csv
saved_training_data: data/processed/saved_training_data.csv
make_dataset.py: src/data/make_dataset.py
build_features.py: src/features/build_features.py
train_model.py: src/models/train_model.py
evaluate_model.py: src/models/evaluate_model.py
daily_update.py: src/models/daily_update.py
actual_season_data: data/processed/new_data_actual_season.csv
teams_stats: data/processed/teams_stats.csv
previous_season: 
  - data/raw/2020_LoL_esports_match_data_from_OraclesElixir.csv
  - data/raw/2021_LoL_esports_match_data_from_OraclesElixir.csv
  - data/raw/2022_LoL_esports_match_data_from_OraclesElixir.csv
  - data/raw/2023_LoL_esports_match_data_from_OraclesElixir.csv
  - data/raw/2024_LoL_esports_match_data_from_OraclesElixir.csv
